#configuration file 
version: '3.9'
#version of the docker compose syntax

services:
  app: #name of service that is running the docker file
    build: 
      context: . #build the context in the current directory
      args:
        - DEV=true
    ports:
      - "8000:8000" #port of the local machine : port of the container
    volumes:
      - ./app:/app #mapping app dir in the app dir of the container --> reflecting local code in the running container in reel time (synch)
    command: > #the command used to run the service --> override it with docker compose run ( by default if we dont specify the command it will use this )
      sh -c "python manage.py runserver 0.0.0.0:8000" 

#using docker-compose build command in cmd to run the docker image using the conf file